#baseURL = "http://example.org/"
#languageCode = "en-us"
#title = "My New Hugo Site"

publishDir = "docs"
canonifyurls = true


baseURL = "https://beginnercppis.github.io/Electric-Sheep/"
defaultContentLanguage = "en"
title = "introduction"
theme = "m10c"

[params]
author = "maki"
description = "simple introduction something like hobby"
[params.style]

 # darkColor = "#2a3738"                                                                                                                                                                                    
 # darkestColor = "#d35050"                                                                                                                                                                                 
   darkColor = "#212121"
 # lightColor = "#f5e3e0"                                                                                                                                                                                   
 # lightestColor = "#f5f5f5"                                                                                                                                                                                
 # primaryColor = "#fff"       